import 'package:flutter/material.dart';

// 배경색
const BACKGROUND_COLOR = Color(0xFFFFFFFF);
const BACKGROUND_GREY_LIGHT_COLOR = Color(0xFFF5F4F1);
const BACKGROUND_GREY_DEEP_COLOR = Color(0xFFCCCBC8);
const BACKGROUND_BLUE_LIGHT_COLOR = Color(0xFFF9FAFB);

// // Primary Colors

// const PRIMARY_DEEP_COLOR = Color(0xFFB6CCD8);

// 메인색
const PRIMARY_COLOR = Color(0xFF3B82F6);
const PRIMARY_LIGHT_COLOR = Color(0xFFEFF6FF);

// 강조색
const ACCENT_LIGHT_COLOR = Color(0xFFD4EAF7);
const ACCENT_COLOR = Color(0xFF71C4EF);
const ACCENT_DEEP_COLOR = Color(0xFF00668C);

// 텍스트 색
const TEXT_COLOR = Color(0xFF1D1C1C);
const SUB_TEXT_COLOR = Color(0xFF313D44);
const DEACTIVATE_TEXT_COLOR = Color(0xFF868686);

// 주차 상태별 색상
// 전체
const PARKING_ALL_BACK_COLOR = Color(0xFFEFF6FF);
const PARKING_ALL_TEXT_COLOR = Color(0xFF3B82F6);

// 입주
const PARKING_RESIDENT_BACK_COLOR = Color(0xFFF0FDF4);
const PARKING_RESIDENT_TEXT_COLOR = Color(0xFF15803D);

// 방문
const PARKING_VISITOR_BACK_COLOR = Color(0xFFFFFBEB);
const PARKING_VISITOR_TEXT_COLOR = Color(0xFFF59E0B);

// 외부
const PARKING_EXTERNAL_BACK_COLOR = Color(0xFFFEF2F2);
const PARKING_EXTERNAL_TEXT_COLOR = Color(0xFFEF4444);
